### PR TITLE
update create-codebook files for page and ch levels

### PR DESCRIPTION
**Pull request by jiyunson**
- put codebook_page.csv in codebooks
- put codebook_chapter.csv in codebooks

### CODE REVIEW

**Review by claudiacsutter — CHANGES_REQUESTED** [review]
Could we add code to also get average eocs per chapter (i.e., two columns, one for chapter_num and one for eoc?)

**Comment by jiyunson** [comment]
@claudiacsutter do you mean an entirely separate data frame? Would that be data we provide to a variety of researchers?

**Comment by jiyunson** [comment]
Ah I was thinking things like that could be on the research website while this would be simply to provide the data and any scripts are documentation of the data we provide. Sent from my iPhoneOn May 1, 2024, at 6:17 AM, claudiacsutter ***@***.***> wrote:﻿
@jiyunson I was more so thinking of just providing the code as an example (i.e., if you're interested in getting an average by chapter, here's how you could do it), without actually saving/providing the datafile - if someone wants to save it, they could just do it on their end?

**Comment by claudiacsutter** [comment]
Ah yes that makes sense to me!

**Review by claudiacsutter — APPROVED** [review]

**Pull request merged**
